server:
  port: 6060

spring:
  application:
    name: corpus
  datasource:
    url: jdbc:mysql://10.10.1.14:3306/skill_platform?characterEncoding=utf-8
    username: ubx
    password: ubx
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter.exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet.login-username: druid
      stat-view-servlet.login-password: druid
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
    
dubbo:
  scan.basePackages: com.ubtechinc.corpus.service
  protocol:
    id: dubbo
    name:  dubbo
    status: server
    port: 20990
  registry:
    id: corpus-registry
    address: zookeeper://10.10.1.43:2181
  application:
    id: corpus-provider
    name: corpus-provider

mybatis-plus:
  mapper-locations: classpath:com/ubtechinc/corpus/mapper/*/*.xml 
  typeAliasesPackage: com.ubtechinc.*.entity