server:
  port: 6061

spring:
  application:
    name: resource
  datasource:
    url: jdbc:mysql://10.10.1.14:3306/skill_platform?characterEncoding=utf-8
    username: ubx
    password: ubx
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter.exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet.login-username: druid
      stat-view-servlet.login-password: druid
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
    
dubbo:
  scan.basePackages: com.ubtechinc.resource.service
  protocol:
    id: dubbo
    name:  dubbo
    status: server
    port: 20991
  registry:
    id: resource-registry
    address: zookeeper://10.10.1.43:2181
  application:
    id: resource-provider
    name: resource-provider

mybatis-plus:
  mapper-locations: classpath:com/ubtechinc/resource/mapper/*/*.xml 
  typeAliasesPackage: com.ubtechinc.*.entity