server:
  port: 6002

spring:
  application:
    name: rule
  datasource:
    url: jdbc:mysql://localhost:3306/skill_platform?characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      web-stat-filter.exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet.login-username: druid
      stat-view-servlet.login-password: druid
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      
dubbo:
  scan.basePackages: com.ubtechinc.rule.service
  application:
    name: rule-provider
    id: rule-provider
  protocol:
    id: zookeeper
    name: dubbo
    port: 20992
    status: server
  registry:
    id: rule-registry
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 30000
    threads: 10

mybatis-plus:
  mapper-locations: classpath:com/ubtechinc/rule/mapper/*/*.xml 
  typeAliasesPackage: com.ubtechinc.*.entity